name: Build nerovaagent installers

on:
  workflow_dispatch:
  push:
    tags:
      - 'agent-v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: amd64
            docker_arch: amd64
          - os: ubuntu-latest
            platform: linux
            arch: arm64
            docker_arch: arm64
          - os: macos-latest
            platform: darwin
            arch: arm64
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}-${{ matrix.arch }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies (Linux)
        if: matrix.platform == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync xvfb ffmpeg xpra fluxbox xz-utils

      - name: Build agent bundle
        env:
          NEROVA_VERSION: ${{ github.ref_name }}
          NEROVA_PLATFORM: ${{ matrix.platform }}
          NEROVA_ARCH: ${{ matrix.arch }}
        run: |
          NEROVA_VERSION=$NEROVA_VERSION NEROVA_PLATFORM=$NEROVA_PLATFORM NEROVA_ARCH=$NEROVA_ARCH bash scripts/build-nerova-release.sh

      - name: Upload installer assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/nerova-agent-${{ github.ref_name }}-${{ matrix.platform }}-${{ matrix.arch }}.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
